language: python
python:
  - "2.7"
  - "3.7"
before_install:
  - sudo apt-get -y install libxml2-dev libxslt-dev python-dev
cache:
  pip: true
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python setup.py -v test
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "SutR6bfuRArHZkPAEVvhN7bImSlPBp3wSdH6H3WO219e2hEjt/oHFvtzSyAMgHNzIP6cZbIr2E/NvVCy6lnVsZwx9cHc94W+edgoydBk/D8JaJA8oRmMRk9ooUA47Us0rgdhv1kZDZxtli8r4IlHcc3hVAbp4BW7P0ac/aL27fVp5tZbKTXsRCKDkSOBglM5JgOypjitVPmkhOrM/3voIYemnfsIYu6p5JiGt/yaVNKZhAId+ORtoQ+d2WMD9EwjtxHQ1OjsYn6iBAob5IUiN47SFw4ZsAMmL69RKKyo/aaVNrirFqv4k6xWEeKG6uQF8dJwRJDrdGUcQIN3DNzsV0eq926aB4LutXE47wbB8t23Us/05e6yFIXkS3dz7nPHss0bH0xbZOFJSilZcyWU2ANrcY+qy+5ARc5f98ZIuZaP5yfmqfW6tn4k7u7oSZxR5ZguW13M8yMl1eUpfyeird89XSn9tgteae15vxiQ834dvcBmgUNbVrYTaXhxfhS9DF4m+JyYDt9Nq8IrnzvUB6QbAFjZHAKnNWF8qnJUruNlVbu11wykc4yh0AnCV+MUR99aLBHMCFwHR0WI1dPOveE7ZtlaoR5zZoIeIzVNOmjLQoTB3PamSl841kkgysvwc9tUKehXvBgv7s9S8/r6RGCipS31olQT+RV95z3FJos="
  on:
    all_branches: true
    python: "3.7"
  distributions: "sdist bdist_wheel"